import Head from "next/head";
import {Inter} from "next/font/google";
import App from "../components/layouts/app";
import React from "react";
import Banner from "../components/banner/banner";
import About from "../components/about/about";
import Contactus from "../components/Contactus/contactus";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
    return (
        <>
            <Head>
                <title>Ubinet</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <App>
                <Banner/>
                <About/>
                <Contactus/>
            </App>
        </>
    );
}
