import Head from "next/head";
import {Inter} from "next/font/google";
import App from "../../components/layouts/app";
import React from "react";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export default function Index() {
  const files = [
    {id:1, name:"2023 4-րդ եռամսյակ", path: "234er.xls"},
    {id:1, name:"2024 1-րդ եռամսյակ", path: "2024 1eramsyak.xls"},
    {id:2, name:"2024 3-րդ եռամսյակ", path: "2024 3eramsyak_db15701b-77d2-4339-83ed-4fe29ff494ab.xls"},
  ]; // List of filenames

  return (
    <>
      <Head>
        <title>Documents</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <App>
        <div style={{ height: '80vh', display: 'flex', alignItems: 'center', width: '90%', margin: 'auto' }}>
          <ul>
            {files.map((file, index) => (
              <li style={{fontSize:'22px', marginTop:'10px'}} key={index}>
                <Link style={{color:'black'}} href={`/api/download/${file.path}`} download>
                  Download {file.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </App>
    </>
  );
}
